[project]
name = "strava-map"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "polyline>=2.0.2",
    "pydantic-settings>=2.9.1",
    "python-dotenv>=1.1.0",
    "redis>=6.1.0",
    "requests>=2.32.3",
]
